---
- name: Setup
  hosts: localhost

  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   # Install Regolith: https://regolith-desktop.com/docs/using-regolith/install/

   - name: Install Regolith
     block:
      - name: Register the Regolith public key
        ansible.builtin.get_url:
         url: https://regolith-desktop.org/regolith.key
         dest: /usr/share/keyrings/regolith-archive-keyring.gpg
        become: true

      - name: Add the repository URL
        ansible.builtin.apt_repository:
         filename: regolith.list
         repo: >
           deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
           https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main
        become: true
