---
- name: Setup
  hosts: localhost
  connection: local

  roles:
    - role: basic

  tasks:

    - name: Install PyCharm
      community.general.snap:
        classic: true
        name: pycharm-professional
      become: true
      tags: installed_with_snap

    - name: Install Chromium
      community.general.snap:
        classic: true
        name: chromium
      become: true
      tags: installed_with_snap

    - name: Install Slack
      community.general.snap:
        classic: true
        name: slack
      become: true
      tags: installed_with_snap

    - name: Install Signal
      # https://signal.org/fr/download/linux/
      become: true
      block:
        - name: Install Signal official public software signing key
          ansible.builtin.get_url:
            url: https://updates.signal.org/desktop/apt/keys.asc
            dest: /usr/share/keyrings/signal-desktop-keyring.asc
            mode: "0644"
        - name: Add the repository URL
          ansible.builtin.apt_repository:
            filename: signal-xenial
            repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.asc] https://updates.signal.org/desktop/apt xenial main
        - name: Install Signal
          ansible.builtin.apt:
            name: signal-desktop
            state: present
            update_cache: true

    - name: Install Flameshot
      become: true
      ansible.builtin.apt:
        name: flameshot
        state: present
        update_cache: true

    - name: Install Spotify
      community.general.snap:
        name: spotify
      become: true
      tags: installed_with_snap

    - name: Install mise
      # https://mise.jdx.dev/getting-started.html#apt
      become: true
      block:
        - name: Install mise public signing key
          ansible.builtin.get_url:
            url: https://mise.jdx.dev/gpg-key.pub
            dest: /etc/apt/keyrings/mise-archive-keyring.asc
            mode: "0644"
        - name: Add the repository URL
          ansible.builtin.apt_repository:
            filename: mise
            repo: deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc arch=amd64] https://mise.jdx.dev/deb stable main
        - name: Install mise
          ansible.builtin.apt:
            name: mise
            state: present
            update_cache: true

    - name: Check if Obsidian is already installed
      # https://help.obsidian.md/Getting+started/Download+and+install+Obsidian#Install+Obsidian+on+Linux
      ansible.builtin.stat:
        path: /usr/bin/obsidian
      register: obsidian

    - name: Find latest Obsidian release
      ansible.builtin.uri:
        url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
        return_content: true
      register: obsidian_release
      when: not obsidian.stat.exists

    - name: Retrieve the download URL
      vars:
        deb_asset: "{{ obsidian_release.json.assets | selectattr('name', 'contains', 'amd64.deb') | join() }}"
      ansible.builtin.set_fact:
        browser_download_url: "{{ deb_asset.browser_download_url }}"
      when: not obsidian.stat.exists

    - name: Download Obsidian
      ansible.builtin.get_url:
        url: "{{ browser_download_url }}"
        dest: /tmp/obsidian.deb
        mode: "0644"
      when: not obsidian.stat.exists

    - name: Install Obsidian
      ansible.builtin.apt:
        deb: /tmp/obsidian.deb
      become: true
      when: not obsidian.stat.exists

    - name: Check if docker is already installed
      # https://docs.docker.com/desktop/install/ubuntu/
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker
    - name: Install Docker official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
      become: true
    - name: Add the repository URL
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [signed-by=/etc/apt/keyrings/docker.asc arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      become: true
    - name: Download the .deb package
      ansible.builtin.get_url:
        url: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.26.1-amd64.deb
        dest: /tmp/docker-desktop.deb
        mode: "0644"
      when: not docker.stat.exists
    - name: Install Docker
      ansible.builtin.apt:
        deb: /tmp/docker-desktop.deb
      become: true
      when: not docker.stat.exists

    - name: Install NvChad
      tags: installed_with_snap
      # https://nvchad.com/docs/quickstart/install
      block:
        - name: Install neovim
          community.general.snap:
            name: nvim
            classic: true
          become: true
        - name: Create a font directory
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.local/share/fonts"
            state: directory
            mode: '0755'
        - name: Install JetBrains Mono Nerd Font
          ansible.builtin.get_url:
            url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf
            dest: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf"
            mode: "0644"
        - name: Clone a repo with separate git directory
          ansible.builtin.git:
            depth: 1
            dest: "{{ ansible_env.HOME }}/.config/nvim"
            repo: https://github.com/NvChad/NvChad
            version: "HEAD"  # noqa: latest
