---
- name: Setup
  hosts: localhost

  tasks:

    - name: Install Regolith
      # https://regolith-desktop.com/docs/using-regolith/install/#ubuntu
      become: true
      block:
        - name: Register the Regolith public key
          ansible.builtin.get_url:
            url: https://regolith-desktop.org/regolith.key
            dest: /usr/share/keyrings/regolith-archive-keyring.asc
            mode: '0644'

        - name: Add the repository URL
          ansible.builtin.apt_repository:
            filename: regolith
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.asc]
              https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main

        - name: Install Regolith
          ansible.builtin.apt:
            name:
              - regolith-desktop
              - regolith-session-flashback
              - regolith-look-nord
            state: present
            update_cache: true

    - name: Install fish
      # https://github.com/fish-shell/fish-shell#packages-for-linux
      become: true
      block:
        - name: Add fish repository from PPA
          ansible.builtin.apt_repository:
            repo: ppa:fish-shell/release-3

        - name: Install fish
          ansible.builtin.apt:
            name: fish
            state: present
            update_cache: true

        - name: Default shell
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            shell: /usr/bin/fish

    - name: Install Fisher and plugins
      # https://github.com/jorgebucaran/fisher#installation
      block:
        - name: Check if Fisher exists
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
          register: fisher

        - name: Download Fisher
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
            dest: /tmp/fisher.fish
            mode: "0644"
          when: not fisher.stat.exists

        - name: Install Fisher
          ansible.builtin.shell: fish -c 'source /tmp/fisher.fish && fisher install jorgebucaran/fisher'
          changed_when: not fisher.stat.exists
