---
- name: Setup
  hosts: localhost

  tasks:

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - curl
        state: present
        update_cache: true

    - name: Install Regolith
      # https://regolith-desktop.com/docs/using-regolith/install/#ubuntu
      become: true
      when: "'regolith-desktop' not in ansible_facts.packages"
      block:
        - name: Register the Regolith public key
          ansible.builtin.get_url:
            url: https://regolith-desktop.org/regolith.key
            dest: /usr/share/keyrings/regolith-archive-keyring.asc
            mode: "0644"
        - name: Add the repository URL
          ansible.builtin.apt_repository:
            filename: regolith
            repo: deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.asc] https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main
        - name: Install Regolith
          ansible.builtin.apt:
            name:
              - regolith-desktop
              - regolith-session-flashback
              - regolith-look-nord
            state: present
            update_cache: true

    - name: Install fish
      # https://github.com/fish-shell/fish-shell#packages-for-linux
      become: true
      block:
        - name: Add fish repository from PPA
          ansible.builtin.apt_repository:
            repo: ppa:fish-shell/release-3
        - name: Install fish
          ansible.builtin.apt:
            name: fish
            state: present
            update_cache: true
        - name: Default shell
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            shell: /usr/bin/fish

    - name: Add ~/.local/bin to PATH
      ansible.builtin.shell: fish_add_path {{ ansible_env.HOME }}/.local/bin
      args:
        executable: /usr/bin/fish
      register: local_bin_path
      changed_when: local_bin_path.rc == 0
      ignore_errors: true

    - name: fisher.fish
      # https://github.com/jorgebucaran/fisher#installation
      block:
        - name: Check if Fisher plugin is installed
          ansible.builtin.shell: functions -q fisher
          args:
            executable: /usr/bin/fish
          changed_when: false
      rescue:
        - name: Download Fisher plugin
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
            dest: /tmp/fisher.fish
            mode: "0644"
        - name: Install Fisher plugin
          ansible.builtin.shell: source /tmp/fisher.fish && fisher install jorgebucaran/fisher
          args:
            executable: /usr/bin/fish
          changed_when: false

    - name: fzf.fish
      # https://github.com/PatrickF1/fzf.fish#installation
      block:
        - name: Check if fzf plugin is installed
          ansible.builtin.shell: fisher list fzf
          args:
            executable: /usr/bin/fish
          changed_when: false
      rescue:
        - name: Install prerequisites
          ansible.builtin.apt:
            name:
              - fzf # fuzzy finder (https://github.com/junegunn/fzf#using-linux-package-managers)
              - fd-find # simple, fast and user-friendly alternative to "find" (https://github.com/sharkdp/fd#on-ubuntu)
              - bat # "cat" clone with syntax highlighting and git integration (https://github.com/sharkdp/bat#on-ubuntu-using-apt)
            state: present
            update_cache: true
            become: true
        - name: Add symlink for fd
          ansible.builtin.file:
            src: /usr/bin/fdfind
            dest: ~/.local/bin/fd
            state: link
        - name: Add symlink for fd
          ansible.builtin.file:
            src: /usr/bin/batcat
            dest: ~/.local/bin/bat
            state: link
        - name: Install fzf plugin
          ansible.builtin.shell: fisher install PatrickF1/fzf.fish
          args:
            executable: /usr/bin/fish
          changed_when: false

    - name: Install other fish plugins
      # done, receive notifications when long processes finish (https://github.com/franciscolourenco/done)
      # sponge, clean fish history from typos automatically (https://github.com/meaningful-ooo/sponge)
      # autopair, auto-complete matching pairs (https://github.com/jorgebucaran/autopair.fish)
      # pure, pretty, minimal, and fast prompt (https://github.com/pure-fish/pure)
      ansible.builtin.shell: |
        fisher install franciscolourenco/done
        fisher install meaningful-ooo/sponge
        fisher install jorgebucaran/autopair.fish
        fisher install pure-fish/pure
      args:
        executable: /usr/bin/fish
      changed_when: false
