---
- name: Setup
  hosts: localhost
  connection: local

  roles:
    - role: base

  tasks:



    - name: Check if Obsidian is already installed
      # https://help.obsidian.md/Getting+started/Download+and+install+Obsidian#Install+Obsidian+on+Linux
      ansible.builtin.stat:
        path: /usr/bin/obsidian
      register: obsidian

    - name: Find latest Obsidian release
      ansible.builtin.uri:
        url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
        return_content: true
      register: obsidian_release
      when: not obsidian.stat.exists

    - name: Retrieve the download URL
      vars:
        deb_asset: "{{ obsidian_release.json.assets | selectattr('name', 'contains', 'amd64.deb') | join() }}"
      ansible.builtin.set_fact:
        browser_download_url: "{{ deb_asset.browser_download_url }}"
      when: not obsidian.stat.exists

    - name: Download Obsidian
      ansible.builtin.get_url:
        url: "{{ browser_download_url }}"
        dest: /tmp/obsidian.deb
        mode: "0644"
      when: not obsidian.stat.exists

    - name: Install Obsidian
      ansible.builtin.apt:
        deb: /tmp/obsidian.deb
      become: true
      when: not obsidian.stat.exists

    - name: Check if docker is already installed
      # https://docs.docker.com/desktop/install/ubuntu/
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker
    - name: Install Docker official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
      become: true
    - name: Add the repository URL
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [signed-by=/etc/apt/keyrings/docker.asc arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      become: true
    - name: Download the .deb package
      ansible.builtin.get_url:
        url: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.26.1-amd64.deb
        dest: /tmp/docker-desktop.deb
        mode: "0644"
      when: not docker.stat.exists
    - name: Install Docker
      ansible.builtin.apt:
        deb: /tmp/docker-desktop.deb
      become: true
      when: not docker.stat.exists

