---
# https://github.com/fish-shell/fish-shell#packages-for-linux
- name: Add fish repository from PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install fish
  become: true
  ansible.builtin.apt:
    name: fish
    state: present
    update_cache: true

- name: Set fish as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish


# # fish abbreviations
# # (https://fishshell.com/docs/current/cmds/abbr.html)
# - name: Add ls abbreviation
#   ansible.builtin.lineinfile:
#     path: ~/.config/fish/config.fish
#     create: true
#     line: abbr --add ls lsd
#     mode: u=rw,g=r,o=r
#
# - name: Add ll abbreviation
#   ansible.builtin.lineinfile:
#     path: ~/.config/fish/config.fish
#     create: true
#     line: abbr --add ll lsd --almost-all --group-directories-first -l
#     mode: u=rw,g=r,o=r
