---
- name: Install apt packages
  ansible.builtin.import_tasks: apt_packages.yml
- name: Install Regolith
  ansible.builtin.import_tasks: regolith.yml
- name: Install fish shell and its plugins
  ansible.builtin.import_tasks: fish.yml
- name: Install NvChad
  ansible.builtin.import_tasks: nvchad.yml
- name: Install Obsidian
  ansible.builtin.import_tasks: obsidian.yml
