---
- name: Install fish shell
  ansible.builtin.import_tasks: fish.yml
# Remove for now, Warp is not adapted with fish...
# - name: Install Warp
#   ansible.builtin.import_tasks: warp.yml
- name: Install APT and Snap packages
  ansible.builtin.import_tasks: packages.yml
- name: Install Regolith
  ansible.builtin.import_tasks: regolith.yml
- name: Install NvChad
  ansible.builtin.import_tasks: nvchad.yml
- name: Install Obsidian
  ansible.builtin.import_tasks: obsidian.yml
- name: Configure GNOME
  ansible.builtin.import_tasks: gnome.yml
