---
# https://nvchad.com/docs/quickstart/install
- name: Install neovim
  become: true
  community.general.snap:
    name: nvim
    classic: true
  tags: installed_with_snap

- name: Create a local font directory ~/.local/share/fonts
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Install JetBrains Mono Nerd Font
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/\
    patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/\
    JetBrainsMonoNerdFont-Regular.ttf"
    mode: u=rw,g=r,o=r

- name: Clone NvChad repository
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    repo: https://github.com/NvChad/starter
    version: "HEAD"  # noqa: latest
