---
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - flameshot
      - git
      - python3-pip
      - python3-venv
      - snapd
    state: present
    update_cache: true

- name: Install pip packages
  ansible.builtin.pip:
    name: pipx

- name: Ensure snap is started and enabled on boot
  become: true
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    name: snapd

- name: Refresh Snap
  become: true
  ansible.builtin.command: snap refresh