---
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - flameshot
      - git
      - python3-pip
      - python3-venv
      - snapd
    state: present
    update_cache: true

- name: Install pip packages
  ansible.builtin.pip:
    name: pipx

- name: Refresh Snap
  ansible.builtin.command: snap refresh