---
# https://regolith-desktop.com/docs/using-regolith/install/#ubuntu
- name: Register Regolith official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://regolith-desktop.org/regolith.key
    dest: /usr/share/keyrings/regolith-keyring.asc
    mode: "0644"

- name: Add Regolith repository URL
  become: true
  ansible.builtin.apt_repository:
    filename: regolith
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-keyring.asc]
      https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main

- name: Install Regolith packages
  become: true
  ansible.builtin.apt:
    name:
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-nord
    state: present
    update_cache: true

- name: Install Status Bar Indicators
  become: true
  ansible.builtin.apt:
    name:
      - i3xrocks-battery
      - i3xrocks-bluetooth
      - i3xrocks-cpu-usage
      - i3xrocks-keyboard-layout
      - i3xrocks-media-player
      - i3xrocks-memory
      - i3xrocks-microphone
      - i3xrocks-net-traffic
      - i3xrocks-rofication
      - i3xrocks-temp
      - i3xrocks-time
      - i3xrocks-updates
      - i3xrocks-volume
      - i3xrocks-weather
      - i3xrocks-wifi
    state: present
    update_cache: true
