---
# https://docs.docker.com/desktop/install/ubuntu/
- name: Check if docker is already installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker

- name: Install Docker official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u=rw,g=r,o=r

- name: Add the repository URL
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb [signed-by=/etc/apt/keyrings/docker.asc arch=amd64]
      https://download.docker.com/linux/ubuntu jammy stable

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups: docker
