---
- name: Create SSH directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519

- name: Configure .gitconfig
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - name: commit.gpgsign
      value: true
    - name: core.editor
      value: nvim
    - name: user.name
      value: Pascal SUN
    - name: gpg.format
      value: ssh
    - name: user.email
      value: 35567930+pascal-sun@users.noreply.github.com
    - name: user.signingkey
      value: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
