---
################################################################################
# - name: Install PyCharm
#   community.general.snap:
#     classic: true
#     name: pycharm-professional
#   become: true
#   tags: installed_with_snap

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: libfuse2
    state: present
    update_cache: true


- name: Check if JetBrains Toolbox App is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/\
    JetBrains/Toolbox/bin/jetbrains-toolbox"
  register: toolbox

- name: Find latest JetBrains Toolbox App release
  ansible.builtin.uri:
    url: "https://data.services.jetbrains.com/\
    products/releases?code=TBA&latest=true&type=release"
    return_content: true
  register: toolbox_release
  when: not toolbox.stat.exists

- name: Retrieve the download URL
  ansible.builtin.set_fact:
    browser_download_url: "{{ toolbox_release.json.TBA.0.downloads.linux.link }}"
  when: not toolbox.stat.exists

- name: Download JetBrains Toolbox App
  ansible.builtin.get_url:
    url: "{{ browser_download_url }}"
    dest: /tmp/jetbrains-toolbox.tar.gz
    mode: u=rw,g=r,o=r
  when: not toolbox.stat.exists

- name: Download and unarchive JetBrains Toolbox App
  ansible.builtin.unarchive:
    src: /tmp/jetbrains-toolbox.tar.gz
    dest: /tmp/jetbrains-toolbox
    extra_opts:
      - --strip-components
      - 1
    remote_src: true
  when: not toolbox.stat.exists

- name: Install JetBrains Toolbox App
  ansible.builtin.shell: /tmp/jetbrains-toolbox
  args:
    executable: /usr/bin/fish
  register: result
  changed_when: true
  failed_when: result.rc != 0
  when: not toolbox.stat.exists
