---
# https://mise.jdx.dev/getting-started.html#apt
- name: Install mise GPG key
  become: true
  ansible.builtin.get_url:
    url: https://mise.jdx.dev/gpg-key.pub
    dest: /etc/apt/keyrings/mise-archive-keyring.asc
    mode: u=rwx,g=rx,o=rx

- name: Add mise repository URL
  become: true
  ansible.builtin.apt_repository:
    filename: mise
    repo: >-
      deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc arch=amd64]
      https://mise.jdx.dev/deb stable main

- name: Install mise package
  become: true
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: true
