---
name: ✨ Lint Ansible Playbook
run-name: ✨ Lint Ansible Playbook
on:
  push:
  workflow_dispatch:
  schedule:
    - cron "0 0 * * SUN"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v6
