---
name: ✨ Lint
"on":
  push:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint for Ansible Playbook
        uses: ansible/ansible-lint@v24

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint for YAML file
        run: yamllint .
