name: 🚀 Run Ansible Playbook
run-name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  with-github-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ansible
      - run: ansible-galaxy install --role-file requirements.yml
      - run: ansible-playbook --syntax-check playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: true
      - run: ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: true
      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml | tee -a ${idempotence}
          tail ${idempotence} | grep --quiet 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: true
  with-docker-container:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo $PATH
      - run: echo $GITHUB_PATH
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: echo $PATH
      - run: echo $GITHUB_PATH
      - run: echo "$HOME/.local/bin" >> $PATH
      - run: echo $PATH
      - run: echo $GITHUB_PATH
      - run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop
      - run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
      - run: apt-get install -y python3-pip
      - run: python3 -m pip install --user ansible
      - run: ansible-galaxy install --role-file requirements.yml
      - run: ansible-playbook --syntax-check playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: true
      - run: ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: true
      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml | tee -a ${idempotence}
          tail ${idempotence} | grep --quiet 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: true
