name: 🚀 Run Ansible Playbook
run-name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:22.04", "ubuntu:24.04"]
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop
      - run: apt-get install -y python3-pip
      - run: pip install ansible-core
      - run: ansible-galaxy install -r requirements.yml
      - run: ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml
