name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-22.04
    steps:
      - name: Pre-install pipx and ansible
        run: sh pre-install.sh
      - name: Run ansible playbook
        run: ansible-playbook playbook.yaml -vvv
