name: 🚀 Run Ansible Playbook
run-name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu:20.04", "ubuntu:22.04", "ubuntu:23.04", "ubuntu:23.10"]
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y ubuntu-desktop
      - run: sh pre-install.sh
      - run: ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yaml
