name: 🚀 Run Ansible Playbook
run-name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yaml
