name: 🚀 Run Ansible Playbook
run-name: 🚀 Run Ansible Playbook
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:22.04", "ubuntu:24.04"]
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y ubuntu-desktop
      - run: apt-get install -y pipx
      - run: pipx ensurepath
      - run: pipx install ansible-core
      - run: ./.local/bin/ansible-galaxy install -r requirements.yml
      - run: ./.local/bin/ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yaml
