name: 🚀 Run Ansible Playbook
run-name: Run Ansible Playbook by ${{ github.actor }} 🚀
on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-22.04
    steps:
      - name: Pre-install pipx and ansible
        run: ./pre-install.sh
      - name: Run ansible playbook
        run: ansible-playbook playbook.yaml -vvv
